<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE docCollection [
<!ELEMENT docCollection ( doc+) >
<!ATTLIST docCollection BASE CDATA #REQUIRED DOCS CDATA #REQUIRED >
<!ELEMENT doc ANY> <!ATTLIST doc DOCR CDATA #REQUIRED PIECE CDATA #REQUIRED
DOCN CDATA #REQUIRED >
<!ELEMENT DOCN ANY>
<!ELEMENT INUM ANY>
<!ELEMENT SIGN ANY>
<!ELEMENT CLAA ANY>
<!ELEMENT CLAB ANY>
<!ELEMENT CLAC ANY>
<!ELEMENT TIDO ANY>
<!ELEMENT TRAD ANY>
<!ELEMENT ACCE ANY>
<!ELEMENT FORM ANY>
<!ELEMENT NUEJ ANY>
<!ELEMENT NUHO ANY>
<!ELEMENT LENG ANY>
<!ELEMENT SERI ANY>
<!ELEMENT TITU ANY>
<!ELEMENT AUTO ANY>
<!ELEMENT FECH ANY>
<!ELEMENT LUGA ANY>
<!ELEMENT TECN ANY>
<!ELEMENT SOPO ANY>
<!ELEMENT DIME ANY>
<!ELEMENT ESCA ANY>
<!ELEMENT COOR ANY>
<!ELEMENT NOTA ANY>
<!ELEMENT DGEO ANY>
<!ELEMENT DONO ANY>
<!ELEMENT DINS ANY>
<!ELEMENT DMAT ANY>
<!ELEMENT ESCO ANY>
<!ELEMENT NOCO ANY>
<!ELEMENT TARJ ANY>
<!ELEMENT IMAG ANY>
<!ELEMENT DOCU ANY>
<!ELEMENT OBSE ANY>
<!ELEMENT INCI ANY>
<!ELEMENT BIBL ANY>
<!ELEMENT INVE ANY>
<!ELEMENT FECA ANY>
<!ELEMENT FACR ANY>
<!ELEMENT USUA ANY>
<!ELEMENT VALO ANY>
<!ELEMENT ARCH ANY>
<!ELEMENT AEDI ANY>
<!ELEMENT LUAC ANY>
<!ELEMENT NIVE ANY>
<!ELEMENT NPRO ANY>
<!ELEMENT VASE ANY>
<!ELEMENT PFAL ANY>
<!ELEMENT IDES ANY>
<!ELEMENT HARC ANY>
<!ELEMENT CORR ANY>
<!ELEMENT ELDO ANY>
<!ELEMENT RNUM ANY>
<!ELEMENT ISAD ANY>
<!ELEMENT USUC ANY>
<!ELEMENT FECR ANY>
<!ELEMENT CORG ANY>
<!ELEMENT LORG ANY>
] >
<docCollection BASE="PLAN" DOCS="11606">
<doc DOCR="500" PIECE="PLAN" DOCN="000000500">
<DOCN>
000000500
</DOCN>
<INUM>
P00000467
</INUM>
<SIGN>
00000467
</SIGN>
<CLAA>
VALENCIA
</CLAA>
<CLAB>
OBRAS HIDRÁULICAS
</CLAB>
<CLAC>
CANAL DE SUECA
</CLAC>
<TIDO>
Plano
</TIDO>
<TRAD>
Original
</TRAD>
<ACCE>
Restringido
</ACCE>
<FORM>
Encuadernado
</FORM>
<NUEJ>
1
</NUEJ>
<NUHO>
1
</NUHO>
<LENG>
Castellano
</LENG>
<SERI>
Proyecto de un canal de navegación de Sueca a Valencia por Don Manuel Sorni.
</SERI>
<TITU>
Línea del canal de Sueca.
</TITU>
<AUTO>
Manuel Sorní (firmado y rubricado)
</AUTO>
<FECH>
18520000
</FECH>
<LUGA>
s.l.
</LUGA>
<TECN>
Tinta negra y roja con aguadas en azul
</TECN>
<SOPO>
Papel
</SOPO>
<DIME>
333 x 1000
</DIME>
<ESCA>
1/10.000
</ESCA>
<COOR>
</COOR>
<NOTA>
</NOTA>
<DGEO>
SUECA (VALENCIA)
</DGEO>
<DONO>
SORNÍ, MANUEL,*ARQUITECTO
</DONO>
<DINS>
</DINS>
<DMAT>
OBRAS HIDRÁULICAS
</DMAT>
<ESCO>
Bueno
</ESCO>
<NOCO>
</NOCO>
<TARJ>
Si
</TARJ>
<IMAG>
Si
</IMAG>
<DOCU>
</DOCU>
<OBSE>
</OBSE>
<INCI>
</INCI>
<BIBL>
</BIBL>
<INVE>
</INVE>
<FECA>
20-oct-08
</FECA>
<FACR>
20131204
</FACR>
<USUA>
monitora
</USUA>
<VALO>
</VALO>
<ARCH>
28079
</ARCH>
<AEDI>
</AEDI>
<LUAC>
</LUAC>
<NIVE>
</NIVE>
<NPRO>
</NPRO>
<VASE>
</VASE>
<PFAL>
</PFAL>
<IDES>
</IDES>
<HARC>
</HARC>
<CORR>
</CORR>
<ELDO>
</ELDO>
<RNUM>
</RNUM>
<ISAD>
ISAD (G)
</ISAD>
<USUC>
</USUC>
<FECR>
</FECR>
<CORG>
PMD
</CORG>
<LORG>
PLANOS, MAPAS Y DIBUJOS
</LORG>
</doc>
<doc DOCR="501" PIECE="PLAN" DOCN="000000501">
<DOCN>
000000501
</DOCN>
<INUM>
P00000468
</INUM>
<SIGN>
00000468
</SIGN>
<CLAA>
VALENCIA
</CLAA>
<CLAB>
OBRAS HIDRÁULICAS
</CLAB>
<CLAC>
CANAL DE SUECA
</CLAC>
<TIDO>
Plano
</TIDO>
<TRAD>
Original
</TRAD>
<ACCE>
Restringido
</ACCE>
<FORM>
Encuadernado
</FORM>
<NUEJ>
1
</NUEJ>
<NUHO>
1
</NUHO>
<LENG>
Castellano
</LENG>
<SERI>
Proyecto de un canal de navegación de Sueca a Valencia por Don Manuel Sorni.
</SERI>
<TITU>
Línea del canal de Sueca.
</TITU>
<AUTO>
Manuel Sorní (firmado y rubricado)
</AUTO>
<FECH>
18520000
</FECH>
<LUGA>
s.l.
</LUGA>
<TECN>
Tinta negra y roja con aguadas en azul y gris
</TECN>
<SOPO>
Papel
</SOPO>
<DIME>
333 x 1000
</DIME>
<ESCA>
1/10.000
</ESCA>
<COOR>
</COOR>
<NOTA>
</NOTA>
<DGEO>
SUECA (VALENCIA)
</DGEO>
<DONO>
SORNÍ, MANUEL,*ARQUITECTO
</DONO>
<DINS>
</DINS>
<DMAT>
OBRAS HIDRÁULICAS
</DMAT>
<ESCO>
Bueno
</ESCO>
<NOCO>
</NOCO>
<TARJ>
Si
</TARJ>
<IMAG>
Si
</IMAG>
<DOCU>
</DOCU>
<OBSE>
</OBSE>
<INCI>
</INCI>
<BIBL>
</BIBL>
<INVE>
</INVE>
<FECA>
20-oct-08
</FECA>
<FACR>
20131204
</FACR>
<USUA>
monitora
</USUA>
<VALO>
</VALO>
<ARCH>
28079
</ARCH>
<AEDI>
</AEDI>
<LUAC>
</LUAC>
<NIVE>
</NIVE>
<NPRO>
</NPRO>
<VASE>
</VASE>
<PFAL>
</PFAL>
<IDES>
</IDES>
<HARC>
</HARC>
<CORR>
</CORR>
<ELDO>
</ELDO>
<RNUM>
</RNUM>
<ISAD>
ISAD (G)
</ISAD>
<USUC>
</USUC>
<FECR>
</FECR>
<CORG>
PMD
</CORG>
<LORG>
PLANOS, MAPAS Y DIBUJOS
</LORG>
</doc>
<doc DOCR="502" PIECE="PLAN" DOCN="000000502">
<DOCN>
000000502
</DOCN>
<INUM>
P00000469
</INUM>
<SIGN>
00000469
</SIGN>
<CLAA>
VALENCIA
</CLAA>
<CLAB>
OBRAS HIDRÁULICAS
</CLAB>
<CLAC>
CANAL DE SUECA
</CLAC>
<TIDO>
Plano
</TIDO>
<TRAD>
Original
</TRAD>
<ACCE>
Restringido
</ACCE>
<FORM>
Encuadernado
</FORM>
<NUEJ>
1
</NUEJ>
<NUHO>
1
</NUHO>
<LENG>
Castellano
</LENG>
<SERI>
Proyecto de un canal de navegación de Sueca a Valencia por Don Manuel Sorni.
</SERI>
<TITU>
Línea del canal de Sueca.
</TITU>
<AUTO>
Manuel Sorní (firmado y rubricado)
</AUTO>
<FECH>
18520000
</FECH>
<LUGA>
s.l.
</LUGA>
<TECN>
Tinta negra y roja con aguadas en azul y gris
</TECN>
<SOPO>
Papel
</SOPO>
<DIME>
333 x 1000
</DIME>
<ESCA>
1/10.000
</ESCA>
<COOR>
</COOR>
<NOTA>
</NOTA>
<DGEO>
SUECA (VALENCIA)
</DGEO>
<DONO>
SORNÍ, MANUEL,*ARQUITECTO
</DONO>
<DINS>
</DINS>
<DMAT>
OBRAS HIDRÁULICAS
</DMAT>
<ESCO>
Bueno
</ESCO>
<NOCO>
</NOCO>
<TARJ>
Si
</TARJ>
<IMAG>
Si
</IMAG>
<DOCU>
</DOCU>
<OBSE>
</OBSE>
<INCI>
</INCI>
<BIBL>
</BIBL>
<INVE>
</INVE>
<FECA>
20-oct-08
</FECA>
<FACR>
20131204
</FACR>
<USUA>
monitora
</USUA>
<VALO>
</VALO>
<ARCH>
28079
</ARCH>
<AEDI>
</AEDI>
<LUAC>
</LUAC>
<NIVE>
</NIVE>
<NPRO>
</NPRO>
<VASE>
</VASE>
<PFAL>
</PFAL>
<IDES>
</IDES>
<HARC>
</HARC>
<CORR>
</CORR>
<ELDO>
</ELDO>
<RNUM>
</RNUM>
<ISAD>
ISAD (G)
</ISAD>
<USUC>
</USUC>
<FECR>
</FECR>
<CORG>
PMD
</CORG>
<LORG>
PLANOS, MAPAS Y DIBUJOS
</LORG>
</doc>
<doc DOCR="503" PIECE="PLAN" DOCN="000000503">
<DOCN>
000000503
</DOCN>
<INUM>
P00000470
</INUM>
<SIGN>
00000470
</SIGN>
<CLAA>
VALENCIA
</CLAA>
<CLAB>
OBRAS HIDRÁULICAS
</CLAB>
<CLAC>
CANAL DE SUECA
</CLAC>
<TIDO>
Plano
</TIDO>
<TRAD>
Original
</TRAD>
<ACCE>
Restringido
</ACCE>
<FORM>
Encuadernado
</FORM>
<NUEJ>
1
</NUEJ>
<NUHO>
1
</NUHO>
<LENG>
Castellano
</LENG>
<SERI>
Proyecto de un canal de navegación de Sueca a Valencia por Don Manuel Sorni.
</SERI>
<TITU>
Perfil del canal de Sueca.
</TITU>
<AUTO>
Manuel Sorní (firmado y rubricado)
</AUTO>
<FECH>
18520000
</FECH>
<LUGA>
s.l.
</LUGA>
<TECN>
Tinta negra y roja con aguadas en naranja y gris
</TECN>
<SOPO>
Papel
</SOPO>
<DIME>
330 x 995
</DIME>
<ESCA>
1/10.000 1/200
</ESCA>
<COOR>
</COOR>
<NOTA>
</NOTA>
<DGEO>
SUECA (VALENCIA)
</DGEO>
<DONO>
SORNÍ, MANUEL,*ARQUITECTO
</DONO>
<DINS>
</DINS>
<DMAT>
OBRAS HIDRÁULICAS
</DMAT>
<ESCO>
Bueno
</ESCO>
<NOCO>
</NOCO>
<TARJ>
Si
</TARJ>
<IMAG>
Si
</IMAG>
<DOCU>
</DOCU>
<OBSE>
</OBSE>
<INCI>
</INCI>
<BIBL>
</BIBL>
<INVE>
</INVE>
<FECA>
20-oct-08
</FECA>
<FACR>
20131204
</FACR>
<USUA>
monitora
</USUA>
<VALO>
</VALO>
<ARCH>
28079
</ARCH>
<AEDI>
</AEDI>
<LUAC>
</LUAC>
<NIVE>
</NIVE>
<NPRO>
</NPRO>
<VASE>
</VASE>
<PFAL>
</PFAL>
<IDES>
</IDES>
<HARC>
</HARC>
<CORR>
</CORR>
<ELDO>
</ELDO>
<RNUM>
</RNUM>
<ISAD>
ISAD (G)
</ISAD>
<USUC>
</USUC>
<FECR>
</FECR>
<CORG>
PMD
</CORG>
<LORG>
PLANOS, MAPAS Y DIBUJOS
</LORG>
</doc>
<doc DOCR="504" PIECE="PLAN" DOCN="000000504">
<DOCN>
000000504
</DOCN>
<INUM>
P00000471
</INUM>
<SIGN>
00000471
</SIGN>
<CLAA>
VALENCIA
</CLAA>
<CLAB>
OBRAS HIDRÁULICAS
</CLAB>
<CLAC>
CANAL DE SUECA
</CLAC>
<TIDO>
Plano
</TIDO>
<TRAD>
Original
</TRAD>
<ACCE>
Restringido
</ACCE>
<FORM>
Encuadernado
</FORM>
<NUEJ>
1
</NUEJ>
<NUHO>
1
</NUHO>
<LENG>
Castellano
</LENG>
<SERI>
Proyecto de un canal de navegación de Sueca a Valencia por Don Manuel Sorni.
</SERI>
<TITU>
Perfil del canal de Sueca.
</TITU>
<AUTO>
Manuel Sorní (firmado y rubricado)
</AUTO>
<FECH>
18520000
</FECH>
<LUGA>
s.l.
</LUGA>
<TECN>
Tinta negra y roja con aguadas en naranja y gris
</TECN>
<SOPO>
Papel
</SOPO>
<DIME>
333 x 1000
</DIME>
<ESCA>
1/10.000 y 1/200
</ESCA>
<COOR>
</COOR>
<NOTA>
</NOTA>
<DGEO>
SUECA (VALENCIA)
</DGEO>
<DONO>
SORNÍ, MANUEL,*ARQUITECTO
</DONO>
<DINS>
</DINS>
<DMAT>
OBRAS HIDRÁULICAS
</DMAT>
<ESCO>
Bueno
</ESCO>
<NOCO>
</NOCO>
<TARJ>
Si
</TARJ>
<IMAG>
Si
</IMAG>
<DOCU>
</DOCU>
<OBSE>
</OBSE>
<INCI>
</INCI>
<BIBL>
</BIBL>
<INVE>
</INVE>
<FECA>
20-oct-08
</FECA>
<FACR>
20131204
</FACR>
<USUA>
monitora
</USUA>
<VALO>
</VALO>
<ARCH>
28079
</ARCH>
<AEDI>
</AEDI>
<LUAC>
</LUAC>
<NIVE>
</NIVE>
<NPRO>
</NPRO>
<VASE>
</VASE>
<PFAL>
</PFAL>
<IDES>
</IDES>
<HARC>
</HARC>
<CORR>
</CORR>
<ELDO>
</ELDO>
<RNUM>
</RNUM>
<ISAD>
ISAD (G)
</ISAD>
<USUC>
</USUC>
<FECR>
</FECR>
<CORG>
PMD
</CORG>
<LORG>
PLANOS, MAPAS Y DIBUJOS
</LORG>
</doc>
<doc DOCR="505" PIECE="PLAN" DOCN="000000505">
<DOCN>
000000505
</DOCN>
<INUM>
P00000472
</INUM>
<SIGN>
00000472
</SIGN>
<CLAA>
VALENCIA
</CLAA>
<CLAB>
OBRAS HIDRÁULICAS
</CLAB>
<CLAC>
CANAL DE SUECA
</CLAC>
<TIDO>
Plano
</TIDO>
<TRAD>
Original
</TRAD>
<ACCE>
Restringido
</ACCE>
<FORM>
Encuadernado
</FORM>
<NUEJ>
1
</NUEJ>
<NUHO>
1
</NUHO>
<LENG>
Castellano
</LENG>
<SERI>
Proyecto de un canal de navegación de Sueca a Valencia por Don Manuel Sorni.
</SERI>
<TITU>
Diseño de sifones, esclusas y puentes.
</TITU>
<AUTO>
Manuel Sorní (firmado y rubricado)
</AUTO>
<FECH>
18520000
</FECH>
<LUGA>
s.l.
</LUGA>
<TECN>
Tinta negra y azul
</TECN>
<SOPO>
Papel
</SOPO>
<DIME>
335 x 500
</DIME>
<ESCA>
1/200
</ESCA>
<COOR>
</COOR>
<NOTA>
</NOTA>
<DGEO>
SUECA (VALENCIA)
</DGEO>
<DONO>
SORNÍ, MANUEL,*ARQUITECTO
</DONO>
<DINS>
</DINS>
<DMAT>
OBRAS HIDRÁULICAS

PUENTES
</DMAT>
<ESCO>
Bueno
</ESCO>
<NOCO>
</NOCO>
<TARJ>
Si
</TARJ>
<IMAG>
Si
</IMAG>
<DOCU>
</DOCU>
<OBSE>
</OBSE>
<INCI>
</INCI>
<BIBL>
</BIBL>
<INVE>
</INVE>
<FECA>
20-oct-08
</FECA>
<FACR>
20131204
</FACR>
<USUA>
monitora
</USUA>
<VALO>
</VALO>
<ARCH>
28079
</ARCH>
<AEDI>
</AEDI>
<LUAC>
</LUAC>
<NIVE>
</NIVE>
<NPRO>
</NPRO>
<VASE>
</VASE>
<PFAL>
</PFAL>
<IDES>
</IDES>
<HARC>
</HARC>
<CORR>
</CORR>
<ELDO>
</ELDO>
<RNUM>
</RNUM>
<ISAD>
ISAD (G)
</ISAD>
<USUC>
</USUC>
<FECR>
</FECR>
<CORG>
PMD
</CORG>
<LORG>
PLANOS, MAPAS Y DIBUJOS
</LORG>
</doc>
<doc DOCR="506" PIECE="PLAN" DOCN="000000506">
<DOCN>
000000506
</DOCN>
<INUM>
P00000473
</INUM>
<SIGN>
00000473
</SIGN>
<CLAA>
ALCUDIA (MALLORCA,
ILLES BALEARS)
</CLAA>
<CLAB>
PARAJES NATURALES
</CLAB>
<CLAC>
ALBUFERA DE ALCUDIA
</CLAC>
<TIDO>
Mapa
</TIDO>
<TRAD>
Original
</TRAD>
<ACCE>
Restringido
</ACCE>
<FORM>
No encuadernado
</FORM>
<NUEJ>
1
</NUEJ>
<NUHO>
1
</NUHO>
<LENG>
Castellano
</LENG>
<SERI>
</SERI>
<TITU>
"Plano de la Albufera Grande de Alcudia y prados circunvecinos [...]"
</TITU>
<AUTO>
[Juan Sorá] (documentado)
[Bartolomé Sureda] (documentado)
</AUTO>
<FECH>
18300820
</FECH>
<LUGA>
s.l.
</LUGA>
<TECN>
Tinta negra con aguadas en varios colores
</TECN>
<SOPO>
Papel
</SOPO>
<DIME>
490 x 652
</DIME>
<ESCA>
2000 varas castellanas [= 92 mm]
</ESCA>
<COOR>
</COOR>
<NOTA>
Contiene leyenda
</NOTA>
<DGEO>
ALBUFERA DE ALCUDIA (MALLORCA, ILLES BALEARS)
</DGEO>
<DONO>
SORÁ, JUAN*

SUREDA, BARTOLOMÉ,*DIRECTOR JUBILADO DE LA FÁBRICA DE LOZA Y CRISTALES
</DONO>
<DINS>
</DINS>
<DMAT>
PRADOS

PARAJES NATURALES

ALBUFERAS
</DMAT>
<ESCO>
Regular
</ESCO>
<NOCO>
Restaurado pero con roturas en bordes
</NOCO>
<TARJ>
Si
</TARJ>
<IMAG>
Si
</IMAG>
<DOCU>
Procede: Caja 7520 / 709
</DOCU>
<OBSE>
Véase 4814
</OBSE>
<INCI>
</INCI>
<BIBL>
</BIBL>
<INVE>
Bartolomé Sureda (1767-1851). Madrid, 1999.
</INVE>
<FECA>
17-oct-08
</FECA>
<FACR>
20150730
</FACR>
<USUA>
javierf
</USUA>
<VALO>
18.030  1999
</VALO>
<ARCH>
28079
</ARCH>
<AEDI>
</AEDI>
<LUAC>
</LUAC>
<NIVE>
</NIVE>
<NPRO>
</NPRO>
<VASE>
</VASE>
<PFAL>
</PFAL>
<IDES>
</IDES>
<HARC>
</HARC>
<CORR>
</CORR>
<ELDO>
</ELDO>
<RNUM>
</RNUM>
<ISAD>
ISAD (G)
</ISAD>
<USUC>
</USUC>
<FECR>
</FECR>
<CORG>
PMD
</CORG>
<LORG>
PLANOS, MAPAS Y DIBUJOS
</LORG>
</doc>
<doc DOCR="507" PIECE="PLAN" DOCN="000000507">
<DOCN>
000000507
</DOCN>
<INUM>
P00000474
</INUM>
<SIGN>
00000474
</SIGN>
<CLAA>
VALENCIA
</CLAA>
<CLAB>
FINCAS RÚSTICAS
</CLAB>
<CLAC>
PALACIO REAL
</CLAC>
<TIDO>
Plano
</TIDO>
<TRAD>
Original
</TRAD>
<ACCE>
Restringido
</ACCE>
<FORM>
No encuadernado
</FORM>
<NUEJ>
1
</NUEJ>
<NUHO>
1
</NUHO>
<LENG>
Castellano
</LENG>
<SERI>
</SERI>
<TITU>
"Plan topográfico geometrico en el que se manifiesta y comprende toda la estensi
ón de las tierras
huertas, jardines, edificios, y demas obras sólidas que encierra toda la posesió
n propiedad de Su
Majestad estramuros de la ciudad de Valencia en el punto del demolido Palacio Re
al ".
</TITU>
<AUTO>
[Joaquín Belda] (atribuido a)
</AUTO>
<FECH>
[1820-1840]
</FECH>
<LUGA>
s.l.
</LUGA>
<TECN>
Aguadas en varios colores
</TECN>
<SOPO>
Papel
</SOPO>
<DIME>
642 x 951
</DIME>
<ESCA>
400 palmos valencianos [= 159 mm.]; 400 palmos castellanos [= 149 mm.]
</ESCA>
<COOR>
</COOR>
<NOTA>
</NOTA>
<DGEO>
VALENCIA
</DGEO>
<DONO>
</DONO>
<DINS>
</DINS>
<DMAT>
PALACIOS

JARDINES

FINCAS RÚSTICAS

FINCAS URBANAS
</DMAT>
<ESCO>
Malo
</ESCO>
<NOCO>
Rotura en pliegue central y cinta
adhesiva
</NOCO>
<TARJ>
Si
</TARJ>
<IMAG>
Si
</IMAG>
<DOCU>
Valencia Carpeta 3
</DOCU>
<OBSE>
</OBSE>
<INCI>
</INCI>
<BIBL>
</BIBL>
<INVE>
</INVE>
<FECA>
17-oct-08
</FECA>
<FACR>
20110922
</FACR>
<USUA>
monitora
</USUA>
<VALO>
</VALO>
<ARCH>
28079
</ARCH>
<AEDI>
</AEDI>
<LUAC>
</LUAC>
<NIVE>
</NIVE>
<NPRO>
</NPRO>
<VASE>
</VASE>
<PFAL>
</PFAL>
<IDES>
</IDES>
<HARC>
</HARC>
<CORR>
</CORR>
<ELDO>
</ELDO>
<RNUM>
</RNUM>
<ISAD>
ISAD (G)
</ISAD>
<USUC>
</USUC>
<FECR>
</FECR>
<CORG>
PMD
</CORG>
<LORG>
PLANOS, MAPAS Y DIBUJOS
</LORG>
</doc>
<doc DOCR="508" PIECE="PLAN" DOCN="000000508">
<DOCN>
000000508
</DOCN>
<INUM>
P00000475
</INUM>
<SIGN>
00000475
</SIGN>
<CLAA>
EL PARDO (MADRID)
</CLAA>
<CLAB>
PALACIOS
</CLAB>
<CLAC>
PALACIO DE VIÑUELAS
</CLAC>
<TIDO>
Plano
</TIDO>
<TRAD>
Original
</TRAD>
<ACCE>
Restringido
</ACCE>
<FORM>
No encuadernado
</FORM>
<NUEJ>
1
</NUEJ>
<NUHO>
1
</NUHO>
<LENG>
Castellano
</LENG>
<SERI>
</SERI>
<TITU>
"Castillo [de Viñuelas] y nuevas cavallerizas". Alzado, perfil y planta.
</TITU>
<AUTO>
Antonio Carlos de Borbón (firmado y rubricado)
</AUTO>
<FECH>
[17600000]
</FECH>
<LUGA>
s.l.
</LUGA>
<TECN>
Tinta negra con aguadas en gris. Tinta sepia para el texto
</TECN>
<SOPO>
Papel entelado
</SOPO>
<DIME>
635 x 1000
</DIME>
<ESCA>
150 pies castellanos [= 273 mm]
</ESCA>
<COOR>
</COOR>
<NOTA>
Contiene leyenda
</NOTA>
<DGEO>
PALACIO DE VIÑUELAS (EL PARDO, MADRID)
</DGEO>
<DONO>
BORBÓN, ANTONIO CARLOS DE,*ARQUITECTO DE OBRAS REALES
</DONO>
<DINS>
REAL SITIO DE EL PARDO

PATRIMONIO REAL
</DINS>
<DMAT>
PALACIOS

CASTILLOS

OBRAS Y REPARACIONES

CABALLERIZAS
</DMAT>
<ESCO>
Malo
</ESCO>
<NOCO>
Roturas
</NOCO>
<TARJ>
Si
</TARJ>
<IMAG>
Si
</IMAG>
<DOCU>
</DOCU>
<OBSE>
</OBSE>
<INCI>
</INCI>
<BIBL>
V. Tovar Martín: El Real Sitio de El Pardo. Madrid, 1995. Pp. 360
</BIBL>
<INVE>
La memoria selectiva 1835-1936. Madrid, 1999.
</INVE>
<FECA>
17-oct-08
</FECA>
<FACR>
20150824
</FACR>
<USUA>
javierf
</USUA>
<VALO>
18.030  1999
</VALO>
<ARCH>
28079
</ARCH>
<AEDI>
</AEDI>
<LUAC>
</LUAC>
<NIVE>
</NIVE>
<NPRO>
</NPRO>
<VASE>
</VASE>
<PFAL>
</PFAL>
<IDES>
</IDES>
<HARC>
</HARC>
<CORR>
</CORR>
<ELDO>
</ELDO>
<RNUM>
</RNUM>
<ISAD>
ISAD (G)
</ISAD>
<USUC>
</USUC>
<FECR>
</FECR>
<CORG>
PMD
</CORG>
<LORG>
PLANOS, MAPAS Y DIBUJOS
</LORG>
</doc>
<doc DOCR="509" PIECE="PLAN" DOCN="000000509">
<DOCN>
000000509
</DOCN>
<INUM>
P00000476
</INUM>
<SIGN>
00000476
</SIGN>
<CLAA>
MADRID
</CLAA>
<CLAB>
CABALLERIZAS
</CLAB>
<CLAC>
VISTA ALEGRE
</CLAC>
<TIDO>
Plano
</TIDO>
<TRAD>
Original
</TRAD>
<ACCE>
Restringido
</ACCE>
<FORM>
No encuadernado
</FORM>
<NUEJ>
1
</NUEJ>
<NUHO>
1
</NUHO>
<LENG>
Castellano
</LENG>
<SERI>
</SERI>
<TITU>
"Proyecto 1º " para las cuadras que deben construirse en la Real Posesión de Vis
ta Alegre en el Sitio
que ocupa en la actualidad la casa de Vacas. Planta y alzado.
</TITU>
<AUTO>
Anónimo
</AUTO>
<FECH>
s.d.
</FECH>
<LUGA>
s.l.
</LUGA>
<TECN>
Tinta negra con aguadas en varios colores
</TECN>
<SOPO>
Papel
</SOPO>
<DIME>
446 x 345
</DIME>
<ESCA>
200 pies castellanos [= 180 mm.]
</ESCA>
<COOR>
</COOR>
<NOTA>
Ángulo inferior derecho, nota manuscrita a lápiz: "devuelto por el arquitecto"
</NOTA>
<DGEO>
VISTA ALEGRE (MADRID)
</DGEO>
<DONO>
</DONO>
<DINS>
REAL POSESIÓN DE VISTA ALEGRE
</DINS>
<DMAT>
CABALLERIZAS
</DMAT>
<ESCO>
Bueno
</ESCO>
<NOCO>
</NOCO>
<TARJ>
Si
</TARJ>
<IMAG>
Si
</IMAG>
<DOCU>
</DOCU>
<OBSE>
Viene acompañado de una hoja anexa con explicación.
</OBSE>
<INCI>
</INCI>
<BIBL>
</BIBL>
<INVE>
</INVE>
<FECA>
17-oct-08
</FECA>
<FACR>
20110922
</FACR>
<USUA>
monitora
</USUA>
<VALO>
</VALO>
<ARCH>
28079
</ARCH>
<AEDI>
</AEDI>
<LUAC>
</LUAC>
<NIVE>
</NIVE>
<NPRO>
</NPRO>
<VASE>
</VASE>
<PFAL>
</PFAL>
<IDES>
</IDES>
<HARC>
</HARC>
<CORR>
</CORR>
<ELDO>
</ELDO>
<RNUM>
</RNUM>
<ISAD>
ISAD (G)
</ISAD>
<USUC>
</USUC>
<FECR>
</FECR>
<CORG>
PMD
</CORG>
<LORG>
PLANOS, MAPAS Y DIBUJOS
</LORG>
</doc>
<doc DOCR="510" PIECE="PLAN" DOCN="000000510">
<DOCN>
000000510
</DOCN>
<INUM>
P00000477
</INUM>
<SIGN>
00000477
</SIGN>
<CLAA>
MADRID
</CLAA>
<CLAB>
CABALLERIZAS
</CLAB>
<CLAC>
VISTA ALEGRE
</CLAC>
<TIDO>
Plano
</TIDO>
<TRAD>
Original
</TRAD>
<ACCE>
Restringido
</ACCE>
<FORM>
No encuadernado
</FORM>
<NUEJ>
1
</NUEJ>
<NUHO>
1
</NUHO>
<LENG>
Castellano
</LENG>
<SERI>
</SERI>
<TITU>
"Proyecto 2º " para las cuadras que deben construirse en la Real Posesión de Vis
ta Alegre en el Sitio
que ocupa en la actualidad la casa de Vacas. Planta y alzado.
</TITU>
<AUTO>
Anónimo
</AUTO>
<FECH>
s.d.
</FECH>
<LUGA>
s.l.
</LUGA>
<TECN>
Tinta negra con aguadas en varios colores
</TECN>
<SOPO>
Papel
</SOPO>
<DIME>
445 x 343
</DIME>
<ESCA>
200 pies castellanos [= 180 mm]
</ESCA>
<COOR>
</COOR>
<NOTA>
Ángulo inferior derecho, nota manuscrita a lápiz: "devuelto por el arquitecto"
</NOTA>
<DGEO>
VISTA ALEGRE (MADRID)
</DGEO>
<DONO>
</DONO>
<DINS>
REAL POSESIÓN DE VISTA ALEGRE
</DINS>
<DMAT>
CABALLERIZAS
</DMAT>
<ESCO>
Bueno
</ESCO>
<NOCO>
</NOCO>
<TARJ>
Si
</TARJ>
<IMAG>
Si
</IMAG>
<DOCU>
</DOCU>
<OBSE>
Viene acompañado de una hoja anexa con explicación
</OBSE>
<INCI>
</INCI>
<BIBL>
</BIBL>
<INVE>
</INVE>
<FECA>
17-oct-08
</FECA>
<FACR>
20110922
</FACR>
<USUA>
monitora
</USUA>
<VALO>
</VALO>
<ARCH>
28079
</ARCH>
<AEDI>
</AEDI>
<LUAC>
</LUAC>
<NIVE>
</NIVE>
<NPRO>
</NPRO>
<VASE>
</VASE>
<PFAL>
</PFAL>
<IDES>
</IDES>
<HARC>
</HARC>
<CORR>
</CORR>
<ELDO>
</ELDO>
<RNUM>
</RNUM>
<ISAD>
ISAD (G)
</ISAD>
<USUC>
</USUC>
<FECR>
</FECR>
<CORG>
PMD
</CORG>
<LORG>
PLANOS, MAPAS Y DIBUJOS
</LORG>
</doc>
<doc DOCR="511" PIECE="PLAN" DOCN="000000511">
<DOCN>
000000511
</DOCN>
<INUM>
P00000478
</INUM>
<SIGN>
00000478
</SIGN>
<CLAA>
MADRID
</CLAA>
<CLAB>
FINCAS RÚSTICAS
</CLAB>
<CLAC>
VISTA ALEGRE
</CLAC>
<TIDO>
Plano
</TIDO>
<TRAD>
Original
</TRAD>
<ACCE>
Restringido
</ACCE>
<FORM>
No encuadernado
</FORM>
<NUEJ>
1
</NUEJ>
<NUHO>
1
</NUHO>
<LENG>
Castellano
</LENG>
<SERI>
</SERI>
<TITU>
"PLANO DE LA REAL POSESIÓN DE VISTA ALEGRE".
</TITU>
<AUTO>
Francisco Pérez (firmado y rubricado)

Emeterio Minguet (firmado y rubricado)
</AUTO>
<FECH>
18490714
</FECH>
<LUGA>
Madrid
</LUGA>
<TECN>
Tinta negra y roja y aguadas en varios colores
</TECN>
<SOPO>
Papel
</SOPO>
<DIME>
668 x 989
</DIME>
<ESCA>
400 estadales [= 749 mm.]
</ESCA>
<COOR>
</COOR>
<NOTA>
Contiene explicación y leyenda.
</NOTA>
<DGEO>
VISTA ALEGRE (MADRID)
</DGEO>
<DONO>
PÉREZ, FRANCISCO*

MINGUET, EMETERIO*
</DONO>
<DINS>
REAL POSESIÓN DE VISTA ALEGRE

F
</DINS>
<DMAT>
FINCAS RÚSTICAS
</DMAT>
<ESCO>
Regular
</ESCO>
<NOCO>
Roturas en bordes y cinta adhesiva en el
verso.
</NOCO>
<TARJ>
Si
</TARJ>
<IMAG>
Si
</IMAG>
<DOCU>
En el verso: Carpeta Madrid nº 22.
</DOCU>
<OBSE>
</OBSE>
<INCI>
</INCI>
<BIBL>
</BIBL>
<INVE>
</INVE>
<FECA>
14-oct-08
</FECA>
<FACR>
20110922
</FACR>
<USUA>
monitora
</USUA>
<VALO>
</VALO>
<ARCH>
28079
</ARCH>
<AEDI>
</AEDI>
<LUAC>
</LUAC>
<NIVE>
</NIVE>
<NPRO>
</NPRO>
<VASE>
</VASE>
<PFAL>
</PFAL>
<IDES>
</IDES>
<HARC>
</HARC>
<CORR>
</CORR>
<ELDO>
</ELDO>
<RNUM>
</RNUM>
<ISAD>
ISAD (G)
</ISAD>
<USUC>
</USUC>
<FECR>
</FECR>
<CORG>
PMD
</CORG>
<LORG>
PLANOS, MAPAS Y DIBUJOS
</LORG>
</doc>
<doc DOCR="512" PIECE="PLAN" DOCN="000000512">
<DOCN>
000000512
</DOCN>
<INUM>
P00000479
</INUM>
<SIGN>
00000479
</SIGN>
<CLAA>
BARCELONA
</CLAA>
<CLAB>
CASAS
</CLAB>
<CLAC>
PALACIO DE LOS REYES
DE ARAGÓN
</CLAC>
<TIDO>
Plano
</TIDO>
<TRAD>
Original
</TRAD>
<ACCE>
Restringido
</ACCE>
<FORM>
No encuadernado
</FORM>
<NUEJ>
1
</NUEJ>
<NUHO>
1
</NUHO>
<LENG>
Castellano
</LENG>
<SERI>
Proyecto de una nueva casa en el antiguo Palacio de los Reyes de Aragón, en Barc
elona.
</SERI>
<TITU>
"Diseño F. Fachada para la nueva Casa que se propone en el local del antiguo Rea
l Palacio de los Señores
Reyes de Aragón que había ocupado el Tribunal de la Inquisición". Alzado.
</TITU>
<AUTO>
Tomás Soler y Ferrer (firmado y rubricado)
</AUTO>
<FECH>
18350528
</FECH>
<LUGA>
Barcelona
</LUGA>
<TECN>
Tinta negra con aguadas en gris
</TECN>
<SOPO>
Papel verjurado
</SOPO>
<DIME>
423 x 529
</DIME>
<ESCA>
70 pies castellanos[= 127 mm]; 100 palmos catalanes [= 122 mm]
</ESCA>
<COOR>
</COOR>
<NOTA>
</NOTA>
<DGEO>
CALLE DE LA TAPINERÍA (BARCELONA)

CALLE DE LA INQUISICIÓN (BARCELONA)

PALACIO DE LOS REYES DE ARAGÓN (BARCELONA)
</DGEO>
<DONO>
SOLER Y FERRER, TOMÁS,*ARQUITECTO DE LA BAILÍA GENERAL DE CATALUÑA
</DONO>
<DINS>
BAILÍA GENERAL DE CATALUÑA
</DINS>
<DMAT>
PALACIOS

CASAS

FINCAS URBANAS

FACHADAS
</DMAT>
<ESCO>
Bueno
</ESCO>
<NOCO>
</NOCO>
<TARJ>
Si
</TARJ>
<IMAG>
Si
</IMAG>
<DOCU>
En el verso: Del expediente: "Cataluña: Proyectos de obras y reparaciones" 5-Jul
io-1837.
"Inquisición: sobre la conveniencia de su completo derribo y Real Orden de esta 
fecha
ordenandolo".
</DOCU>
<OBSE>
El antiguo Palacio estaba situado entre las calles de la Tapinería y de la Inqui
sición
</OBSE>
<INCI>
</INCI>
<BIBL>
</BIBL>
<INVE>
</INVE>
<FECA>
16-oct-08
PALACIO DE LOS REYES DE ARAGÓN
(BARCELONA)
</FECA>
<FACR>
20111124
</FACR>
<USUA>
monitora
</USUA>
<VALO>
</VALO>
<ARCH>
28079
</ARCH>
<AEDI>
</AEDI>
<LUAC>
</LUAC>
<NIVE>
</NIVE>
<NPRO>
</NPRO>
<VASE>
</VASE>
<PFAL>
</PFAL>
<IDES>
</IDES>
<HARC>
</HARC>
<CORR>
</CORR>
<ELDO>
</ELDO>
<RNUM>
</RNUM>
<ISAD>
ISAD (G)
</ISAD>
<USUC>
</USUC>
<FECR>
</FECR>
<CORG>
PMD
</CORG>
<LORG>
PLANOS, MAPAS Y DIBUJOS
</LORG>
</doc>
<doc DOCR="513" PIECE="PLAN" DOCN="000000513">
<DOCN>
000000513
</DOCN>
<INUM>
P00000480
</INUM>
<SIGN>
00000480
</SIGN>
<CLAA>
BARCELONA
</CLAA>
<CLAB>
CASAS
</CLAB>
<CLAC>
PALACIO DE LOS REYES
DE ARAGÓN
</CLAC>
<TIDO>
Plano
</TIDO>
<TRAD>
Original
</TRAD>
<ACCE>
Restringido
</ACCE>
<FORM>
No encuadernado
</FORM>
<NUEJ>
1
</NUEJ>
<NUHO>
1
</NUHO>
<LENG>
Castellano
</LENG>
<SERI>
Proyecto de una nueva casa en el antiguo Palacio de los Reyes de Aragón, en Barc
elona.
</SERI>
<TITU>
"Plano A. Proyecto para el plan terreno". Planta.
</TITU>
<AUTO>
Tomás Soler y Ferrer (firmado y rubricado).
</AUTO>
<FECH>
18350528
</FECH>
<LUGA>
Barcelona
</LUGA>
<TECN>
Tinta negra y aguadas en varios colores
</TECN>
<SOPO>
Papel verjurado
</SOPO>
<DIME>
422 x 530
</DIME>
<ESCA>
70 pies castellanos[= 127 mm.]; 100 palmos catalanes [= 122 mm.]
</ESCA>
<COOR>
</COOR>
<NOTA>
</NOTA>
<DGEO>
CALLE DE LA TAPINERÍA (BARCELONA)

CALLE DE LA INQUISICIÓN (BARCELONA)

PALACIO DE LOS REYES DE ARAGÓN (BARCELONA)
</DGEO>
<DONO>
SOLER Y FERRER, TOMÁS,*ARQUITECTO DE LA BAILÍA GENERAL DE CATULUÑA
</DONO>
<DINS>
BAILÍA GENERAL DE CATULUÑA
</DINS>
<DMAT>
PALACIOS

CASAS

FINCAS URBANAS
</DMAT>
<ESCO>
Regular
</ESCO>
<NOCO>
Roturas en bordes.
</NOCO>
<TARJ>
Si
</TARJ>
<IMAG>
Si
</IMAG>
<DOCU>
</DOCU>
<OBSE>
El antiguo Palacio estaba situado entre las calles de la Tapinería y de la Inqui
sición.
</OBSE>
<INCI>
</INCI>
<BIBL>
</BIBL>
<INVE>
</INVE>
<FECA>
16-oct-08
E ARAGÓN
(BARCELONA)
</FECA>
<FACR>
20111124
</FACR>
<USUA>
monitora
</USUA>
<VALO>
</VALO>
<ARCH>
28079
</ARCH>
<AEDI>
</AEDI>
<LUAC>
</LUAC>
<NIVE>
</NIVE>
<NPRO>
</NPRO>
<VASE>
</VASE>
<PFAL>
</PFAL>
<IDES>
</IDES>
<HARC>
</HARC>
<CORR>
</CORR>
<ELDO>
</ELDO>
<RNUM>
</RNUM>
<ISAD>
ISAD (G)
</ISAD>
<USUC>
</USUC>
<FECR>
</FECR>
<CORG>
PMD
</CORG>
<LORG>
PLANOS, MAPAS Y DIBUJOS
</LORG>
</doc>
<doc DOCR="514" PIECE="PLAN" DOCN="000000514">
<DOCN>
000000514
</DOCN>
<INUM>
P00000481
</INUM>
<SIGN>
00000481
</SIGN>
<CLAA>
BARCELONA
</CLAA>
<CLAB>
CASAS
</CLAB>
<CLAC>
PALACIO DE LOS REYES
DE ARAGÓN
</CLAC>
<TIDO>
Plano
</TIDO>
<TRAD>
Original
</TRAD>
<ACCE>
Restringido
</ACCE>
<FORM>
No encuadernado
</FORM>
<NUEJ>
1
</NUEJ>
<NUHO>
1
</NUHO>
<LENG>
Castellano
</LENG>
<SERI>
Proyecto de una nueva casa en el antiguo Palacio de los Reyes de Aragón, en Barc
elona.
</SERI>
<TITU>
"Plano B. Proyecto para los entresuelos".
</TITU>
<AUTO>
Tomás Soler y Ferrer (firmado y rubricado)
</AUTO>
<FECH>
18350528
</FECH>
<LUGA>
Barcelona
</LUGA>
<TECN>
Tinta negra con aguadas en varios colores
</TECN>
<SOPO>
Papel verjurado
</SOPO>
<DIME>
421 x 531
</DIME>
<ESCA>
70 pies castellanos [= 127 mm]; 100 palmos catalanes [= 122 mm]
</ESCA>
<COOR>
</COOR>
<NOTA>
</NOTA>
<DGEO>
CALLE DE LA TAPINERÍA (BARCELONA)

CALLE DE LA INQUISICIÓN (BARCELONA)

PALACIO DE LOS REYES DE ARAGÓN (BARCELONA)
</DGEO>
<DONO>
SOLER Y FERRER, TOMÁS,*ARQUITECTO DE LA BAILÍA GENERAL DE CATALUÑA
</DONO>
<DINS>
BAILÍA GENERAL DE CATALUÑA
</DINS>
<DMAT>
PALACIOS

CASAS

FINCAS URBANAS
</DMAT>
<ESCO>
Bueno
</ESCO>
<NOCO>
</NOCO>
<TARJ>
Si
</TARJ>
<IMAG>
Si
</IMAG>
<DOCU>
</DOCU>
<OBSE>
El antiguo Palacio estaba situado entre las calles de la Tapinería y de la Inqui
sición
</OBSE>
<INCI>
</INCI>
<BIBL>
</BIBL>
<INVE>
</INVE>
<FECA>
16-oct-08
E ARAGÓN
(BARCELONA)
</FECA>
<FACR>
20111124
</FACR>
<USUA>
monitora
</USUA>
<VALO>
</VALO>
<ARCH>
28079
</ARCH>
<AEDI>
</AEDI>
<LUAC>
</LUAC>
<NIVE>
</NIVE>
<NPRO>
</NPRO>
<VASE>
</VASE>
<PFAL>
</PFAL>
<IDES>
</IDES>
<HARC>
</HARC>
<CORR>
</CORR>
<ELDO>
</ELDO>
<RNUM>
</RNUM>
<ISAD>
ISAD (G)
</ISAD>
<USUC>
</USUC>
<FECR>
</FECR>
<CORG>
PMD
</CORG>
<LORG>
PLANOS, MAPAS Y DIBUJOS
</LORG>
</doc>
<doc DOCR="515" PIECE="PLAN" DOCN="000000515">
<DOCN>
000000515
</DOCN>
<INUM>
P00000482
</INUM>
<SIGN>
00000482
</SIGN>
<CLAA>
BARCELONA
</CLAA>
<CLAB>
CASAS
</CLAB>
<CLAC>
PALACIO DE LOS REYES
DE ARAGÓN
</CLAC>
<TIDO>
Plano
</TIDO>
<TRAD>
Original
</TRAD>
<ACCE>
Restringido
</ACCE>
<FORM>
Encuadernado
</FORM>
<NUEJ>
1
</NUEJ>
<NUHO>
1
</NUHO>
<LENG>
Castellano
</LENG>
<SERI>
Proyecto de una nueva casa en el antiguo Palacio de los Reyes de Aragón, en Barc
elona.
</SERI>
<TITU>
"Plano C. Proyecto para el piso principal". Planta.
</TITU>
<AUTO>
Thomas Soler y Ferrer (firmado y rubricado).
</AUTO>
<FECH>
18350528
</FECH>
<LUGA>
Barcelona
</LUGA>
<TECN>
Tinta negra y aguadas en varios colores
</TECN>
<SOPO>
Papel verjurado
</SOPO>
<DIME>
425 x 530
</DIME>
<ESCA>
70 pies castellanos [= 111 mm.]; 100 palmos catalanes [= mm.]
</ESCA>
<COOR>
</COOR>
<NOTA>
</NOTA>
<DGEO>
CALLE DE LA TAPINERÍA (BARCELONA)

CALLE DE LA INQUISICIÓN (BARCELONA)

PALACIO DE LOS REYES DE ARAGÓN (BARCELONA)
</DGEO>
<DONO>
SOLER Y FERRER, TOMÁS,*ARQUITECTO DE LA BAILÍA GENERAL DE CATULUÑA
</DONO>
<DINS>
BAILÍA GENERAL DE CATULUÑA
</DINS>
<DMAT>
PALACIOS

CASAS

FINCAS URBANAS
</DMAT>
<ESCO>
Bueno
</ESCO>
<NOCO>
</NOCO>
<TARJ>
Si
</TARJ>
<IMAG>
Si
</IMAG>
<DOCU>
</DOCU>
<OBSE>
El antiguo Palacio estaba situado entre las calles de la Tapinería y de la Inqui
sición.
</OBSE>
<INCI>
</INCI>
<BIBL>
</BIBL>
<INVE>
</INVE>
<FECA>
16-oct-08
E ARAGÓN
(BARCELONA)
</FECA>
<FACR>
20111124
</FACR>
<USUA>
monitora
</USUA>
<VALO>
</VALO>
<ARCH>
28079
</ARCH>
<AEDI>
</AEDI>
<LUAC>
</LUAC>
<NIVE>
</NIVE>
<NPRO>
</NPRO>
<VASE>
</VASE>
<PFAL>
</PFAL>
<IDES>
</IDES>
<HARC>
</HARC>
<CORR>
</CORR>
<ELDO>
</ELDO>
<RNUM>
</RNUM>
<ISAD>
ISAD (G)
</ISAD>
<USUC>
</USUC>
<FECR>
</FECR>
<CORG>
PMD
</CORG>
<LORG>
PLANOS, MAPAS Y DIBUJOS
</LORG>
</doc>
<doc DOCR="516" PIECE="PLAN" DOCN="000000516">
<DOCN>
000000516
</DOCN>
<INUM>
P00000483
</INUM>
<SIGN>
00000483
</SIGN>
<CLAA>
BARCELONA
</CLAA>
<CLAB>
CASAS
</CLAB>
<CLAC>
PALACIO DE LOS REYES
DE ARAGÓN
</CLAC>
<TIDO>
Plano
</TIDO>
<TRAD>
Original
</TRAD>
<ACCE>
Restringido
</ACCE>
<FORM>
No encuadernado
</FORM>
<NUEJ>
1
</NUEJ>
<NUHO>
1
</NUHO>
<LENG>
Castellano
</LENG>
<SERI>
Proyecto de una nueva casa en el antiguo Palacio de los Reyes de Aragón, en Barc
elona.
</SERI>
<TITU>
"Plano D. Proyecto para el piso segundo".
</TITU>
<AUTO>
Tomás Soler y Ferrer (firmado y rubricado)
</AUTO>
<FECH>
18350528
</FECH>
<LUGA>
Barcelona
</LUGA>
<TECN>
Tinta negra con aguadas en varios colores
</TECN>
<SOPO>
Papel verjurado
</SOPO>
<DIME>
421 x 530
</DIME>
<ESCA>
70 pies castellanos[= 127 mm]; 100 palmos catalanes [= 123 mm]
</ESCA>
<COOR>
</COOR>
<NOTA>
</NOTA>
<DGEO>
CALLE DE LA TAPINERÍA (BARCELONA)

CALLE DE LA INQUISICIÓN (BARCELONA)

PALACIO DE LOS REYES DE ARAGÓN (BARCELONA)
</DGEO>
<DONO>
SOLER Y FERRER, TOMÁS,*ARQUITECTO DE LA BAILÍA GENERAL DE CATALUÑA
</DONO>
<DINS>
BAILÍA GENERAL DE CATALUÑA
</DINS>
<DMAT>
PALACIOS

CASAS

FINCAS URBANAS
</DMAT>
<ESCO>
Regular
</ESCO>
<NOCO>
Roturas en bordes
</NOCO>
<TARJ>
Si
</TARJ>
<IMAG>
Si
</IMAG>
<DOCU>
</DOCU>
<OBSE>
El antiguo Palacio estaba situado entre las calles de la Tapinería y de la Inqui
sición
</OBSE>
<INCI>
</INCI>
<BIBL>
</BIBL>
<INVE>
</INVE>
<FECA>
16-oct-08
E ARAGÓN
(BARCELONA)
</FECA>
<FACR>
20111124
</FACR>
<USUA>
monitora
</USUA>
<VALO>
</VALO>
<ARCH>
28079
</ARCH>
<AEDI>
</AEDI>
<LUAC>
</LUAC>
<NIVE>
</NIVE>
<NPRO>
</NPRO>
<VASE>
</VASE>
<PFAL>
</PFAL>
<IDES>
</IDES>
<HARC>
</HARC>
<CORR>
</CORR>
<ELDO>
</ELDO>
<RNUM>
</RNUM>
<ISAD>
ISAD (G)
</ISAD>
<USUC>
</USUC>
<FECR>
</FECR>
<CORG>
PMD
</CORG>
<LORG>
PLANOS, MAPAS Y DIBUJOS
</LORG>
</doc>
<doc DOCR="517" PIECE="PLAN" DOCN="000000517">
<DOCN>
000000517
</DOCN>
<INUM>
P00000484
</INUM>
<SIGN>
00000484
</SIGN>
<CLAA>
BARCELONA
</CLAA>
<CLAB>
CASAS
</CLAB>
<CLAC>
PALACIO DE LOS REYES
DE ARAGÓN
</CLAC>
<TIDO>
Plano
</TIDO>
<TRAD>
Original
</TRAD>
<ACCE>
Restringido
</ACCE>
<FORM>
No encuadernado
</FORM>
<NUEJ>
1
</NUEJ>
<NUHO>
1
</NUHO>
<LENG>
Castellano
</LENG>
<SERI>
Proyecto de una nueva casa en el antiguo Palacio de los Reyes de Aragón, en Barc
elona.
</SERI>
<TITU>
"Plano E. Proyecto para el piso tercero".
</TITU>
<AUTO>
Tomás Soler y Ferrer (firmado y rubricado).
</AUTO>
<FECH>